/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedWeeklyRouteImport } from './routes/_authenticated/weekly'
import { Route as AuthenticatedValuesRouteImport } from './routes/_authenticated/values'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSelfRouteImport } from './routes/_authenticated/self'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMonthlyGoalsRouteImport } from './routes/_authenticated/monthly-goals'
import { Route as AuthenticatedMindsetRouteImport } from './routes/_authenticated/mindset'
import { Route as AuthenticatedInnerSeasonsRouteImport } from './routes/_authenticated/inner-seasons'
import { Route as AuthenticatedInfluencesRouteImport } from './routes/_authenticated/influences'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedDayRouteImport } from './routes/_authenticated/day'
import { Route as AuthenticatedCycleRouteImport } from './routes/_authenticated/cycle'
import { Route as AuthenticatedBeliefsRouteImport } from './routes/_authenticated/beliefs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWeeklyRoute = AuthenticatedWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValuesRoute = AuthenticatedValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelfRoute = AuthenticatedSelfRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyGoalsRoute =
  AuthenticatedMonthlyGoalsRouteImport.update({
    id: '/monthly-goals',
    path: '/monthly-goals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMindsetRoute = AuthenticatedMindsetRouteImport.update({
  id: '/mindset',
  path: '/mindset',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInnerSeasonsRoute =
  AuthenticatedInnerSeasonsRouteImport.update({
    id: '/inner-seasons',
    path: '/inner-seasons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfluencesRoute = AuthenticatedInfluencesRouteImport.update({
  id: '/influences',
  path: '/influences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDayRoute = AuthenticatedDayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCycleRoute = AuthenticatedCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBeliefsRoute = AuthenticatedBeliefsRouteImport.update({
  id: '/beliefs',
  path: '/beliefs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/beliefs': typeof AuthenticatedBeliefsRoute
  '/cycle': typeof AuthenticatedCycleRoute
  '/day': typeof AuthenticatedDayRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/influences': typeof AuthenticatedInfluencesRoute
  '/inner-seasons': typeof AuthenticatedInnerSeasonsRoute
  '/mindset': typeof AuthenticatedMindsetRoute
  '/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/self': typeof AuthenticatedSelfRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/values': typeof AuthenticatedValuesRoute
  '/weekly': typeof AuthenticatedWeeklyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/beliefs': typeof AuthenticatedBeliefsRoute
  '/cycle': typeof AuthenticatedCycleRoute
  '/day': typeof AuthenticatedDayRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/influences': typeof AuthenticatedInfluencesRoute
  '/inner-seasons': typeof AuthenticatedInnerSeasonsRoute
  '/mindset': typeof AuthenticatedMindsetRoute
  '/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/self': typeof AuthenticatedSelfRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/values': typeof AuthenticatedValuesRoute
  '/weekly': typeof AuthenticatedWeeklyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/beliefs': typeof AuthenticatedBeliefsRoute
  '/_authenticated/cycle': typeof AuthenticatedCycleRoute
  '/_authenticated/day': typeof AuthenticatedDayRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/influences': typeof AuthenticatedInfluencesRoute
  '/_authenticated/inner-seasons': typeof AuthenticatedInnerSeasonsRoute
  '/_authenticated/mindset': typeof AuthenticatedMindsetRoute
  '/_authenticated/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/self': typeof AuthenticatedSelfRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/values': typeof AuthenticatedValuesRoute
  '/_authenticated/weekly': typeof AuthenticatedWeeklyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beliefs'
    | '/cycle'
    | '/day'
    | '/habits'
    | '/influences'
    | '/inner-seasons'
    | '/mindset'
    | '/monthly-goals'
    | '/profile'
    | '/reports'
    | '/reviews'
    | '/self'
    | '/settings'
    | '/values'
    | '/weekly'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/beliefs'
    | '/cycle'
    | '/day'
    | '/habits'
    | '/influences'
    | '/inner-seasons'
    | '/mindset'
    | '/monthly-goals'
    | '/profile'
    | '/reports'
    | '/reviews'
    | '/self'
    | '/settings'
    | '/values'
    | '/weekly'
    | '/auth/reset-password'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/beliefs'
    | '/_authenticated/cycle'
    | '/_authenticated/day'
    | '/_authenticated/habits'
    | '/_authenticated/influences'
    | '/_authenticated/inner-seasons'
    | '/_authenticated/mindset'
    | '/_authenticated/monthly-goals'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/reviews'
    | '/_authenticated/self'
    | '/_authenticated/settings'
    | '/_authenticated/values'
    | '/_authenticated/weekly'
    | '/auth/reset-password'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/weekly': {
      id: '/_authenticated/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AuthenticatedWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/values': {
      id: '/_authenticated/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof AuthenticatedValuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/self': {
      id: '/_authenticated/self'
      path: '/self'
      fullPath: '/self'
      preLoaderRoute: typeof AuthenticatedSelfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly-goals': {
      id: '/_authenticated/monthly-goals'
      path: '/monthly-goals'
      fullPath: '/monthly-goals'
      preLoaderRoute: typeof AuthenticatedMonthlyGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mindset': {
      id: '/_authenticated/mindset'
      path: '/mindset'
      fullPath: '/mindset'
      preLoaderRoute: typeof AuthenticatedMindsetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inner-seasons': {
      id: '/_authenticated/inner-seasons'
      path: '/inner-seasons'
      fullPath: '/inner-seasons'
      preLoaderRoute: typeof AuthenticatedInnerSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/influences': {
      id: '/_authenticated/influences'
      path: '/influences'
      fullPath: '/influences'
      preLoaderRoute: typeof AuthenticatedInfluencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/day': {
      id: '/_authenticated/day'
      path: '/day'
      fullPath: '/day'
      preLoaderRoute: typeof AuthenticatedDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycle': {
      id: '/_authenticated/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof AuthenticatedCycleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beliefs': {
      id: '/_authenticated/beliefs'
      path: '/beliefs'
      fullPath: '/beliefs'
      preLoaderRoute: typeof AuthenticatedBeliefsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBeliefsRoute: typeof AuthenticatedBeliefsRoute
  AuthenticatedCycleRoute: typeof AuthenticatedCycleRoute
  AuthenticatedDayRoute: typeof AuthenticatedDayRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedInfluencesRoute: typeof AuthenticatedInfluencesRoute
  AuthenticatedInnerSeasonsRoute: typeof AuthenticatedInnerSeasonsRoute
  AuthenticatedMindsetRoute: typeof AuthenticatedMindsetRoute
  AuthenticatedMonthlyGoalsRoute: typeof AuthenticatedMonthlyGoalsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSelfRoute: typeof AuthenticatedSelfRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedValuesRoute: typeof AuthenticatedValuesRoute
  AuthenticatedWeeklyRoute: typeof AuthenticatedWeeklyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBeliefsRoute: AuthenticatedBeliefsRoute,
  AuthenticatedCycleRoute: AuthenticatedCycleRoute,
  AuthenticatedDayRoute: AuthenticatedDayRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedInfluencesRoute: AuthenticatedInfluencesRoute,
  AuthenticatedInnerSeasonsRoute: AuthenticatedInnerSeasonsRoute,
  AuthenticatedMindsetRoute: AuthenticatedMindsetRoute,
  AuthenticatedMonthlyGoalsRoute: AuthenticatedMonthlyGoalsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSelfRoute: AuthenticatedSelfRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedValuesRoute: AuthenticatedValuesRoute,
  AuthenticatedWeeklyRoute: AuthenticatedWeeklyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
